#!/usr/bin/python

import M2Crypto, sys

print 'generating server keys'
Cert = M2Crypto.RSA.gen_key(4096, 65537)
Cert.save_key("src/server_auth.key", cipher=None)
Cert.save_pub_key("src/server_auth.pub")
print 'done'
